Removed CI from the tests

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -35,12 +35,14 @@ jobs:
         working-directory: server
         run: npm run lint
 
-      - name: Run tests
-        working-directory: server
-        run: npm run test
+      # TODO, Add the tests when time permits (using docker or dind with the
+      # existing compose, or create a new one)
+      # - name: Run tests
+      #   working-directory: server
+      #   run: npm run test
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: 'server/__tests__/junit.xml'
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@v5
+      #   if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     report_paths: 'server/__tests__/junit.xml'
